### ISSUE TITLE
Best practices when using "let"

### ISSUE THREAD

**Issue by hlascelles** [tricycle/rspec-sorbet#13]
We use `let` quite often in our tests. eg

```
let(:foo) { SomeBar.new }
```

I can well imagine that would require quite some work to add type checking for (resolving at the access line). Just in case I have missed something obvious, does `rspec-sorbet` have anything that could help here? Is it planned, or do you have any guidance as to what we should do?

**Comment by samuelgiles** [comment]
Hi @hlascelles 👋   rspec-sorbet is mostly focused on letting instance/class/object doubles pass through Sorbet's runtime type checking, i.e:

```ruby
class Foo
  extend T::Sig
  
  sig { params(bar: MyThing) }
  def initialize(bar)
    @bar = bar
  end
end

...

let(:my_thing) { instance_double(MyThing) }

it 'works' do
  Foo.new(my_thing)
end
```

This tends to work pretty well in @tricyle projects and just helps make sure that where we are passing doubles into methods we're at least passing the right kind of double.

I'm not sure if that helps answer your question?

**Comment by hlascelles** [comment]
Yes, thank you! I can fully understand the utility of the above - and I can well understand getting `let` to be typed (or even the rest of rspec tests) would be a real trial. One for another day I think. Cheers.
